/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_backport_webp_WebPFactory */

#ifndef _Included_android_backport_webp_WebPFactory
#define _Included_android_backport_webp_WebPFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_backport_webp_WebPFactory
 * Method:    nativeDecodeByteArray
 * Signature: ([BLandroid/graphics/BitmapFactory/Options;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_android_backport_webp_WebPFactory_nativeDecodeByteArray
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     android_backport_webp_WebPFactory
 * Method:    nativeEncodeBitmap
 * Signature: (Landroid/graphics/Bitmap;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_backport_webp_WebPFactory_nativeEncodeBitmap
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
